phonetic_mapping = {
    "American": {
    "A": {"Arabic": "أ", "Indonesian": "A", "Indian": "A", "Turkish": "A"},
    "B": {"Arabic": "ب", "Indonesian": "B", "Indian": "B", "Turkish": "B"},
    "C": {"Arabic": "ك/ س", "Indonesian": "C", "Indian": "C", "Turkish": "C"},
    "D": {"Arabic": "د", "Indonesian": "D", "Indian": "D", "Turkish": "D"},
    "E": {"Arabic": "إ", "Indonesian": "E", "Indian": "E", "Turkish": "E"},
    "F": {"Arabic": "ف", "Indonesian": "F", "Indian": "F", "Turkish": "F"},
    "G": {"Arabic": "ج", "Indonesian": "G", "Indian": "G", "Turkish": "G"},
    "H": {"Arabic": "ه", "Indonesian": "H", "Indian": "H", "Turkish": "H"},
    "I": {"Arabic": "ي", "Indonesian": "I", "Indian": "I", "Turkish": "I"},
    "J": {"Arabic": "ج", "Indonesian": "J", "Indian": "J", "Turkish": "J"},
    "K": {"Arabic": "ك", "Indonesian": "K", "Indian": "K", "Turkish": "K"},
    "L": {"Arabic": "ل", "Indonesian": "L", "Indian": "L", "Turkish": "L"},
    "M": {"Arabic": "م", "Indonesian": "M", "Indian": "M", "Turkish": "M"},
    "N": {"Arabic": "ن", "Indonesian": "N", "Indian": "N", "Turkish": "N"},
    "O": {"Arabic": "و", "Indonesian": "O", "Indian": "O", "Turkish": "O"},
    "P": {"Arabic": "ب", "Indonesian": "P", "Indian": "P", "Turkish": "P"},
    "Q": {"Arabic": "ق", "Indonesian": "Q", "Indian": "Q"},
    "R": {"Arabic": "ر", "Indonesian": "R", "Indian": "R", "Turkish": "R"},
    "S": {"Arabic": "س", "Indonesian": "S", "Indian": "S", "Turkish": "S"},
    "T": {"Arabic": "ت", "Indonesian": "T", "Indian": "T", "Turkish": "T"},
    "U": {"Arabic": "و", "Indonesian": "U", "Indian": "U", "Turkish": "U"},
    "V": {"Arabic": "ف", "Indonesian": "V", "Indian": "V", "Turkish": "V"},
    "W": {"Arabic": "و", "Indonesian": "W", "Indian": "W"},
    "Y": {"Arabic": "ي", "Indonesian": "Y", "Indian": "Y", "Turkish": "Y"},
    "Z": {"Arabic": "ز", "Indonesian": "Z", "Indian": "Z", "Turkish": "Z"}
}
,

    "Arabic": {
    "أ": {"American": "A", "Indonesian": "A", "Indian": "A", "Turkish": "A"},
    "ب": {"American": "B", "Indonesian": "B", "Indian": "B", "Turkish": "B"},
    "ك": {"American": "K", "Indonesian": "K", "Indian": "K", "Turkish": "K"},
    "د": {"American": "D", "Indonesian": "D", "Indian": "D", "Turkish": "D"},
    "إ": {"American": "E", "Indonesian": "E", "Indian": "E", "Turkish": "E"},
    "ف": {"American": "F", "Indonesian": "F", "Indian": "F", "Turkish": "F"},
    "ج": {"American": "G", "Indonesian": "G", "Indian": "G", "Turkish": "G"},
    "ه": {"American": "H", "Indonesian": "H", "Indian": "H", "Turkish": "H"},
    "و": {"American": "U", "Indonesian": "U", "Indian": "U", "Turkish": "U"},
    "ي": {"American": "Y", "Indonesian": "Y", "Indian": "Y", "Turkish": "Y"},
    "ر": {"American": "R", "Indonesian": "R", "Indian": "R", "Turkish": "R"},
    "س": {"American": "S", "Indonesian": "S", "Indian": "S", "Turkish": "S"},
    "ت": {"American": "T", "Indonesian": "T", "Indian": "T", "Turkish": "T"},
    "ز": {"American": "Z", "Indonesian": "Z", "Indian": "Z", "Turkish": "Z"}
}
,
"Indian": {
    "A": {"Arabic": "أ", "American": "A", "Indonesian": "A", "Turkish": "A"},
    "B": {"Arabic": "ب", "American": "B", "Indonesian": "B", "Turkish": "B"},
    "C": {"Arabic": "س", "American": "C", "Indonesian": "C", "Turkish": "C"},
    "D": {"Arabic": "د", "American": "D", "Indonesian": "D", "Turkish": "D"},
    "F": {"Arabic": "ف", "American": "F", "Indonesian": "F", "Turkish": "F"},
    "G": {"Arabic": "ج", "American": "G", "Indonesian": "G", "Turkish": "G"},
    "H": {"Arabic": "ه", "American": "H", "Indonesian": "H", "Turkish": "H"},
    "I": {"Arabic": "ي", "American": "I", "Indonesian": "I", "Turkish": "I"},
    "J": {"Arabic": "ج", "American": "J", "Indonesian": "J", "Turkish": "J"},
    "K": {"Arabic": "ك", "American": "K", "Indonesian": "K", "Turkish": "K"},
    "L": {"Arabic": "ل", "American": "L", "Indonesian": "L", "Turkish": "L"},
    "M": {"Arabic": "م", "American": "M", "Indonesian": "M", "Turkish": "M"},
    "N": {"Arabic": "ن", "American": "N", "Indonesian": "N", "Turkish": "N"},
    "O": {"Arabic": "و", "American": "O", "Indonesian": "O", "Turkish": "O"},
    "P": {"Arabic": "ب", "American": "P", "Indonesian": "P", "Turkish": "P"},
    "Q": {"Arabic": "ق", "American": "Q", "Indonesian": "Q"},  
    "R": {"Arabic": "ر", "American": "R", "Indonesian": "R", "Turkish": "R"},
    "S": {"Arabic": "س", "American": "S", "Indonesian": "S", "Turkish": "S"},
    "T": {"Arabic": "ت", "American": "T", "Indonesian": "T", "Turkish": "T"},
    "U": {"Arabic": "و", "American": "U", "Indonesian": "U", "Turkish": "U"},
    "V": {"Arabic": "ف", "American": "V", "Indonesian": "V", "Turkish": "V"},
    "W": {"Arabic": "و", "American": "W", "Indonesian": "W"},  
    "Y": {"Arabic": "ي", "American": "Y", "Indonesian": "Y", "Turkish": "Y"},
    "Z": {"Arabic": "ز", "American": "Z", "Indonesian": "Z", "Turkish": "Z"}
}
,

"Indonesian": {
    "A": {"Arabic": "أ", "American": "A", "Indian": "A", "Turkish": "A"},
    "B": {"Arabic": "ب", "American": "B", "Indian": "B", "Turkish": "B"},
    "C": {"Arabic": "س", "American": "C", "Indian": "C", "Turkish": "C"},
    "D": {"Arabic": "د", "American": "D", "Indian": "D", "Turkish": "D"},
    "E": {"Arabic": "إ", "American": "E", "Indian": "E", "Turkish": "E"},
    "F": {"Arabic": "ف", "American": "F", "Indian": "F", "Turkish": "F"},
    "G": {"Arabic": "ج", "American": "G", "Indian": "G", "Turkish": "G"},
    "H": {"Arabic": "ه", "American": "H", "Indian": "H", "Turkish": "H"},
    "I": {"Arabic": "إ", "American": "I", "Indian": "I", "Turkish": "I"},
    "J": {"Arabic": "ج", "American": "J", "Indian": "J", "Turkish": "J"},
    "K": {"Arabic": "ك", "American": "K", "Indian": "K", "Turkish": "K"},
    "L": {"Arabic": "ل", "American": "L", "Indian": "L", "Turkish": "L"},
    "M": {"Arabic": "م", "American": "M", "Indian": "M", "Turkish": "M"},
    "N": {"Arabic": "ن", "American": "N", "Indian": "N", "Turkish": "N"},
    "O": {"Arabic": "و", "American": "O", "Indian": "O", "Turkish": "O"},
    "P": {"Arabic": "ب", "American": "P", "Indian": "P", "Turkish": "P"},
    "Q": {"Arabic": "ق", "American": "Q", "Indian": "Q"},  
    "R": {"Arabic": "ر", "American": "R", "Indian": "R", "Turkish": "R"},
    "S": {"Arabic": "س", "American": "S", "Indian": "S", "Turkish": "S"},
    "T": {"Arabic": "ت", "American": "T", "Indian": "T", "Turkish": "T"},
    "U": {"Arabic": "و", "American": "U", "Indian": "U", "Turkish": "U"},
    "V": {"Arabic": "ف", "American": "V", "Indian": "V", "Turkish": "V"},
    "W": {"Arabic": "و", "American": "W", "Indian": "W"},  
    "Y": {"Arabic": "ي", "American": "Y", "Indian": "Y", "Turkish": "Y"},
    "Z": {"Arabic": "ز", "American": "Z", "Indian": "Z", "Turkish": "Z"}
}
,
"Turkish": {
    "A": {"Arabic": "أ", "American": "A", "Indonesian": "A", "Indian": "A"},
    "B": {"Arabic": "ب", "American": "B", "Indonesian": "B", "Indian": "B"},
    "C": {"Arabic": "ج", "American": "C", "Indonesian": "C", "Indian": "C"},
    "D": {"Arabic": "د", "American": "D", "Indonesian": "D", "Indian": "D"},
    "E": {"Arabic": "إ", "American": "E", "Indonesian": "E", "Indian": "E"},
    "F": {"Arabic": "ف", "American": "F", "Indonesian": "F", "Indian": "F"},
    "G": {"Arabic": "ج", "American": "G", "Indonesian": "G", "Indian": "G"},
    "H": {"Arabic": "ه", "American": "H", "Indonesian": "H", "Indian": "H"},
    "I": {"Arabic": "إ", "American": "I", "Indonesian": "I", "Indian": "I"},
    "J": {"Arabic": "ج", "American": "J", "Indonesian": "J", "Indian": "J"},
    "K": {"Arabic": "ك", "American": "K", "Indonesian": "K", "Indian": "K"},
    "L": {"Arabic": "ل", "American": "L", "Indonesian": "L", "Indian": "L"},
    "M": {"Arabic": "م", "American": "M", "Indonesian": "M", "Indian": "M"},
    "N": {"Arabic": "ن", "American": "N", "Indonesian": "N", "Indian": "N"},
    "O": {"Arabic": "و", "American": "O", "Indonesian": "O", "Indian": "O"},
    "P": {"Arabic": "ب", "American": "P", "Indonesian": "P", "Indian": "P"},
    "R": {"Arabic": "ر", "American": "R", "Indonesian": "R", "Indian": "R"},
    "S": {"Arabic": "س", "American": "S", "Indonesian": "S", "Indian": "S"},
    "T": {"Arabic": "ت", "American": "T", "Indonesian": "T", "Indian": "T"},
    "U": {"Arabic": "و", "American": "U", "Indonesian": "U", "Indian": "U"},
    "V": {"Arabic": "ف", "American": "V", "Indonesian": "V", "Indian": "V"},
    "Y": {"Arabic": "ي", "American": "Y", "Indonesian": "Y", "Indian": "Y"},
    "Z": {"Arabic": "ز", "American": "Z", "Indonesian": "Z", "Indian": "Z"}
}

}
